// app/layout.tsx

import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "../context/ThemeContext";
import { SkillsProvider } from "../context/SkillsContext";
import ToastProvider from "./components/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Skill Enhancement Platform",
  description: "Generated by create next app",
};

// This new function correctly handles the viewport settings
export const generateViewport = (): Viewport => {
  return {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1, // Optional: Prevents zooming on mobile, good for an app-like feel
    userScalable: false, // Optional: Paired with maximumScale
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* You can add other global tags here if needed, like custom fonts or scripts */}
      </head>
      <body className={inter.className}>
        <ThemeProvider>
          <SkillsProvider>
            {children}
            <ToastProvider />
          </SkillsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}