// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "../context/ThemeContext";
import { SkillsProvider } from "../context/SkillsContext";
import ToastProvider from "./components/ToastProvider"; // 1. Import ToastProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Skill Enhancement Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <SkillsProvider>
            {children}
            <ToastProvider /> {/* 2. Add it here */}
          </SkillsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}